ARG BUILD_FROM=ghcr.io/hassio-addons/base:20.1.1
FROM ${BUILD_FROM}

RUN \
    set -x \
    && apk add --no-cache --virtual .build-dependencies \
        build-base \
        linux-headers \
	libusb-dev \
	git \
	python3 \
	py3-pip

RUN git clone https://github.com/mvp/uhubctl.git /tmp/uhubctl && \
    cd /tmp/uhubctl && make && make install

COPY . /app
WORKDIR /app
RUN pip3 install -r requirements.txt

RUN chmod a+x run.sh

CMD ["/app/run.sh"]
